# Generated by Django 3.2 on 2022-05-27 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookitem_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('26fc98cc-bfd6-4d64-a537-ee5ed5e3a907'), editable=False),
        ),
    ]
