# Generated by Django 3.2 on 2022-05-27 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_bookitem_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookitem',
            old_name='Book',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('68e0f285-2c64-4210-ada6-d06714246996'), editable=False),
        ),
    ]
