# Generated by Django 3.2 on 2022-05-27 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20220527_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('91a7addd-95c1-4dc0-b5a7-98033d3d3203'), editable=False),
        ),
    ]
